### ISSUE TITLE
Gnamod UI mod drag drop items to toolbar drops item on ground

### ISSUE THREAD

**Issue by SirFrostingham** [Ragsy2145/Ragsy-Get-Real#1]
- Connect to A18 server with Gnamod UI mod for A18 with 2560x1440 resolution
- drag an item from inventory to lower right vertical quick bar
- item falls on ground

**Comment by Ragsy2145** [comment]
The very top row section of Inventory is where you drag items too that is where the quickbar has been placed and not to the r/h quickbar , this is HaidrGna's Modlet that I am hosting for him .  
Reasoning behind this from Haidr is that as you are selecting item from 'within inventory so you only have to drag within the inventory to the top a few rows at the most and not have to drag acoss screen' .... so coming from vanilla its old habits and even I did the drag across to r/h side initially .  

The quickbar allows you to see the items and select from it and that part functions the same as vanilla.

Hope this Helps 
Ragsy !!
